/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package napsprzedazprognoza;

import java.awt.Cursor;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import napsprzedazprognoza.excel.ExcelExporter;
import napsprzedazprognoza.models.NapvObiektyWPrzedsiebVO;
import napsprzedazprognoza.models.WyliczKwotaRocznaDTO;
import napsprzedazprognoza.renderer.NumberRenderer;
import napsprzedazprognoza.services.NapServices;

/**
 *
 * @author k.skowronski
 */
public class ZestawieniePlanRocznySzczegolowy extends javax.swing.JFrame {

    private NapServices napServ = NapServices.getInstance();
    
    private List<NapvObiektyWPrzedsiebVO> joList = napServ.pobierzObiektyFirmy();
    
    final JPanel panel = new JPanel();
    
    
    /**
     * Creates new form ZestawieniePlanRocznySzczegolowy
     */
    public ZestawieniePlanRocznySzczegolowy() {

        initComponents();
        
        setDefaultCloseOperation( JFrame.DISPOSE_ON_CLOSE );
        
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        jTextData.setText( dateFormat.format(date) );
        
      //  przeliczDane( jTextData.getText(), jComboDywizja.getSelectedItem().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextData = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboDywizja = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Zestawienie szczegolowe");

        jLabel2.setText("Na dzień:");

        jTextData.setText("_null");

        jButton1.setText("excel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboDywizja.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ALL", "C", "Z" }));

        jButton2.setText("Odśwież");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboDywizja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 959, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboDywizja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // excel
        
        TableModel model = jTable1.getModel();
        
        ExcelExporter csvExp = new ExcelExporter();
        String ret = csvExp.ExportTable(model, this);
        
        if ( ret.equals("OK") )
        {
            JOptionPane.showMessageDialog(panel, "Zapisane", "Info", JOptionPane.INFORMATION_MESSAGE);
        } 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // odświeżanie:
        this.setCursor( Cursor.getPredefinedCursor( Cursor.WAIT_CURSOR ) );
        przeliczDane( jTextData.getText(), jComboDywizja.getSelectedItem().toString());
        this.setCursor( Cursor.getDefaultCursor() );
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZestawieniePlanRocznySzczegolowy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZestawieniePlanRocznySzczegolowy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZestawieniePlanRocznySzczegolowy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZestawieniePlanRocznySzczegolowy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZestawieniePlanRocznySzczegolowy().setVisible(true);
            }
        });
    }
    
    private void przeliczDane( String naDzien, String dywizja ){
        
        int rok = 2016; //TODO
        
        DefaultTableModel tm = (DefaultTableModel) jTable1.getModel();

        
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(jTable1.getModel());
        jTable1.setRowSorter(sorter);
        
        tm.getDataVector().removeAllElements();
        tm.fireTableDataChanged();
        tm.setColumnCount(0);
        
     
        
        tm.addColumn("Rodzaj");
        tm.addColumn("OB");
        tm.addColumn("Kwartał");
        
        int ilLat = 6;
        // pętla po latach
        for ( int i = 0 ; i < ilLat ; i = i + 1  )
        {
           tm.addColumn( rok + i ); 
        }
        
        for ( int q = 1 ; q <= 4 ; q = q + 1 )
        {
            for ( NapvObiektyWPrzedsiebVO jo : joList )
            {
                WyliczKwotaRocznaDTO  wylRocznePlan01 = napServ.zestawienieRodznePodajSzczegolowe(rok, "plan", dywizja, naDzien, "Q"+q, jo.getObPelnyKod() );
                WyliczKwotaRocznaDTO  wylRocznePlan02 = napServ.zestawienieRodznePodajSzczegolowe(rok + 1, "plan", dywizja, naDzien, "Q"+q, jo.getObPelnyKod() );
                WyliczKwotaRocznaDTO  wylRocznePlan03 = napServ.zestawienieRodznePodajSzczegolowe(rok + 2, "plan", dywizja, naDzien, "Q"+q, jo.getObPelnyKod() );
                WyliczKwotaRocznaDTO  wylRocznePlan04 = napServ.zestawienieRodznePodajSzczegolowe(rok + 3, "plan", dywizja, naDzien, "Q"+q, jo.getObPelnyKod() );
                WyliczKwotaRocznaDTO  wylRocznePlan05 = napServ.zestawienieRodznePodajSzczegolowe(rok + 4, "plan", dywizja, naDzien, "Q"+q, jo.getObPelnyKod() );
                WyliczKwotaRocznaDTO  wylRocznePlan06 = napServ.zestawienieRodznePodajSzczegolowe(rok + 5, "plan", dywizja, naDzien, "Q"+q, jo.getObPelnyKod() );
                Object[] dok0 = { "plan", jo.getObPelnyKod(), "Q"+q 
                        , wylRocznePlan01.getKwotaIlosc()
                        , wylRocznePlan02.getKwotaIlosc()
                        , wylRocznePlan03.getKwotaIlosc()
                        , wylRocznePlan04.getKwotaIlosc()
                        , wylRocznePlan05.getKwotaIlosc()
                        , wylRocznePlan06.getKwotaIlosc()
                    };
                    tm.addRow(dok0);
                
                    
                //next
                WyliczKwotaRocznaDTO  wylRoczneKontrakt01 = napServ.zestawienieRodznePodajSzczegolowe(rok, "kontrakt", dywizja, naDzien, "Q"+q, jo.getObPelnyKod() );
                WyliczKwotaRocznaDTO  wylRoczneKontrakt02 = napServ.zestawienieRodznePodajSzczegolowe(rok + 1, "kontrakt", dywizja, naDzien, "Q"+q, jo.getObPelnyKod() );
                WyliczKwotaRocznaDTO  wylRoczneKontrakt03 = napServ.zestawienieRodznePodajSzczegolowe(rok + 2, "kontrakt", dywizja, naDzien, "Q"+q, jo.getObPelnyKod() );
                WyliczKwotaRocznaDTO  wylRoczneKontrakt04 = napServ.zestawienieRodznePodajSzczegolowe(rok + 3, "kontrakt", dywizja, naDzien, "Q"+q, jo.getObPelnyKod() );
                WyliczKwotaRocznaDTO  wylRoczneKontrakt05 = napServ.zestawienieRodznePodajSzczegolowe(rok + 4, "kontrakt", dywizja, naDzien, "Q"+q, jo.getObPelnyKod() );
                WyliczKwotaRocznaDTO  wylRoczneKontrakt06 = napServ.zestawienieRodznePodajSzczegolowe(rok + 5, "kontrakt", dywizja, naDzien, "Q"+q, jo.getObPelnyKod() );
                Object[] dok1 = { "kontrakt", jo.getObPelnyKod(), "Q"+q 
                        ,wylRoczneKontrakt01.getKwotaIlosc()
                        ,wylRoczneKontrakt02.getKwotaIlosc()
                        ,wylRoczneKontrakt03.getKwotaIlosc()
                        ,wylRoczneKontrakt04.getKwotaIlosc()
                        ,wylRoczneKontrakt05.getKwotaIlosc()
                        ,wylRoczneKontrakt06.getKwotaIlosc()
                    };
                    tm.addRow(dok1);
                 
                    
                //next    
                WyliczKwotaRocznaDTO  wylRoczneOdnowienie01 = napServ.zestawienieRodznePodajSzczegolowe(rok, "odnowienie", dywizja, naDzien, "Q"+q, jo.getObPelnyKod() );
                WyliczKwotaRocznaDTO  wylRoczneOdnowienie02 = napServ.zestawienieRodznePodajSzczegolowe(rok + 1, "odnowienie", dywizja, naDzien, "Q"+q, jo.getObPelnyKod() );
                WyliczKwotaRocznaDTO  wylRoczneOdnowienie03 = napServ.zestawienieRodznePodajSzczegolowe(rok + 2, "odnowienie", dywizja, naDzien, "Q"+q, jo.getObPelnyKod() );
                WyliczKwotaRocznaDTO  wylRoczneOdnowienie04 = napServ.zestawienieRodznePodajSzczegolowe(rok + 3, "odnowienie", dywizja, naDzien, "Q"+q, jo.getObPelnyKod() );
                WyliczKwotaRocznaDTO  wylRoczneOdnowienie05 = napServ.zestawienieRodznePodajSzczegolowe(rok + 4, "odnowienie", dywizja, naDzien, "Q"+q, jo.getObPelnyKod() );
                WyliczKwotaRocznaDTO  wylRoczneOdnowienie06 = napServ.zestawienieRodznePodajSzczegolowe(rok + 5, "odnowienie", dywizja, naDzien, "Q"+q, jo.getObPelnyKod() );
                Object[] dok2 = { "odnowienie", jo.getObPelnyKod(), "Q"+q
                        ,wylRoczneOdnowienie01.getKwotaIlosc()
                        ,wylRoczneOdnowienie02.getKwotaIlosc()
                        ,wylRoczneOdnowienie03.getKwotaIlosc()
                        ,wylRoczneOdnowienie04.getKwotaIlosc()
                        ,wylRoczneOdnowienie05.getKwotaIlosc()
                        ,wylRoczneOdnowienie06.getKwotaIlosc()
                    };
                    tm.addRow(dok2); 
                    
                    
                //next    
                Object[] dok3 = { "nowe", jo.getObPelnyKod(), "Q"+q 
                        , wylRocznePlan01.getKwotaIlosc().subtract( wylRoczneKontrakt01.getKwotaIlosc().add(wylRoczneOdnowienie01.getKwotaIlosc()) )
                        , wylRocznePlan02.getKwotaIlosc().subtract( wylRoczneKontrakt02.getKwotaIlosc().add(wylRoczneOdnowienie02.getKwotaIlosc()) )
                        , wylRocznePlan03.getKwotaIlosc().subtract( wylRoczneKontrakt03.getKwotaIlosc().add(wylRoczneOdnowienie03.getKwotaIlosc()) )
                        , wylRocznePlan04.getKwotaIlosc().subtract( wylRoczneKontrakt04.getKwotaIlosc().add(wylRoczneOdnowienie04.getKwotaIlosc()) )
                        , wylRocznePlan05.getKwotaIlosc().subtract( wylRoczneKontrakt05.getKwotaIlosc().add(wylRoczneOdnowienie05.getKwotaIlosc()) )
                        , wylRocznePlan06.getKwotaIlosc().subtract( wylRoczneKontrakt06.getKwotaIlosc().add(wylRoczneOdnowienie06.getKwotaIlosc()) )
                    };
                    tm.addRow(dok3);    
            }
            
            
        }
        
        
                TableColumnModel tcm = jTable1.getColumnModel();
                DecimalFormat df2 = new DecimalFormat( "#,###,###,##0.00" );
                tcm.getColumn(3).setCellRenderer( new NumberRenderer( df2 ) );
                tcm.getColumn(4).setCellRenderer( new NumberRenderer( df2 ) );
                tcm.getColumn(5).setCellRenderer( new NumberRenderer( df2 ) );
                tcm.getColumn(6).setCellRenderer( new NumberRenderer( df2 ) );
                tcm.getColumn(7).setCellRenderer( new NumberRenderer( df2 ) );
                tcm.getColumn(8).setCellRenderer( new NumberRenderer( df2 ) );
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboDywizja;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextData;
    // End of variables declaration//GEN-END:variables
}
